const data = [

    {
        id: 1,
        model: "Hyundai Ioniq",
        year: 2016,
        mileage: 174194,
        status: "Свободен",
        driver: "Сидоров И.",
        rating: 4.5,
        trips: 3348,
        fuel: "Hybrid",
        class: "Economy",
        plate: "T532AA-77",
        service: "2023-04-06",
    },

    {
        id: 2,
        model: "Kia Ceed",
        year: 2019,
        mileage: 294951,
        status: "На заказе",
        driver: "Михайлов С.",
        rating: 4.6,
        trips: 14246,
        fuel: "Petrol",
        class: "Standard",
        plate: "E559TH-77",
        service: "2025-04-08",
    },

    {
        id: 3,
        model: "Toyota Prius",
        year: 2018,
        mileage: 251571,
        status: "Свободен",
        driver: "Сидоров С.",
        rating: 4.9,
        trips: 11529,
        fuel: "Hybrid",
        class: "Economy",
        plate: "B194MB-77",
        service: "2024-01-03",
    },

    {
        id: 4,
        model: "Toyota Camry",
        year: 2020,
        mileage: 52780,
        status: "На заказе",
        driver: "Михайлов И.",
        rating: 4.9,
        trips: 12903,
        fuel: "Petrol",
        class: "Comfort",
        plate: "B665HX-77",
        service: "2024-09-25",
    },

    {
        id: 5,
        model: "Toyota Camry",
        year: 2019,
        mileage: 66466,
        status: "Свободен",
        driver: "Кузнецов П.",
        rating: 4.9,
        trips: 8128,
        fuel: "Petrol",
        class: "Comfort",
        plate: "B489HO-77",
        service: "2024-10-12",
    },

    {
        id: 6,
        model: "Toyota Camry",
        year: 2018,
        mileage: 224081,
        status: "Свободен",
        driver: "Смирнов И.",
        rating: 4.5,
        trips: 6107,
        fuel: "Petrol",
        class: "Comfort",
        plate: "P846EC-77",
        service: "2024-04-18",
    },

    {
        id: 7,
        model: "Tesla Model 3",
        year: 2020,
        mileage: 145141,
        status: "На заказе",
        driver: "Иванов С.",
        rating: 4.7,
        trips: 10836,
        fuel: "Electric",
        class: "Business",
        plate: "M374BE-77",
        service: "2025-07-24",
    },

    {
        id: 8,
        model: "Ford Focus",
        year: 2021,
        mileage: 141477,
        status: "На заказе",
        driver: "Попов М.",
        rating: 4.0,
        trips: 5075,
        fuel: "Diesel",
        class: "Standard",
        plate: "E862PP-77",
        service: "2023-09-27",
    },

    {
        id: 9,
        model: "Ford Focus",
        year: 2022,
        mileage: 239400,
        status: "Свободен",
        driver: "Сидоров А.",
        rating: 4.3,
        trips: 2043,
        fuel: "Diesel",
        class: "Standard",
        plate: "B256XC-77",
        service: "2025-03-22",
    },

    {
        id: 10,
        model: "Tesla Model 3",
        year: 2017,
        mileage: 231728,
        status: "Свободен",
        driver: "Соколов А.",
        rating: 4.1,
        trips: 876,
        fuel: "Electric",
        class: "Business",
        plate: "X838BX-77",
        service: "2025-06-25",
    },

    {
        id: 11,
        model: "Renault Logan",
        year: 2020,
        mileage: 208349,
        status: "Свободен",
        driver: "Попов Д.",
        rating: 4.3,
        trips: 9130,
        fuel: "Petrol",
        class: "Economy",
        plate: "P880CP-77",
        service: "2025-07-23",
    },

    {
        id: 12,
        model: "Hyundai Ioniq",
        year: 2020,
        mileage: 296161,
        status: "На заказе",
        driver: "Сидоров О.",
        rating: 4.6,
        trips: 17878,
        fuel: "Hybrid",
        class: "Economy",
        plate: "A713KO-77",
        service: "2023-01-20",
    },

    {
        id: 13,
        model: "Hyundai Ioniq",
        year: 2021,
        mileage: 191225,
        status: "Свободен",
        driver: "Кузнецов В.",
        rating: 4.8,
        trips: 3306,
        fuel: "Hybrid",
        class: "Economy",
        plate: "Y597BP-77",
        service: "2025-02-23",
    },

    {
        id: 14,
        model: "Skoda Octavia",
        year: 2018,
        mileage: 279184,
        status: "На обслуживании",
        driver: "Сидоров П.",
        rating: 4.4,
        trips: 14365,
        fuel: "Petrol",
        class: "Standard",
        plate: "E652YY-77",
        service: "2023-07-25",
    },

    {
        id: 15,
        model: "VW Passat",
        year: 2022,
        mileage: 225779,
        status: "Свободен",
        driver: "Михайлов М.",
        rating: 3.9,
        trips: 7862,
        fuel: "Diesel",
        class: "Comfort",
        plate: "B446AT-77",
        service: "2024-07-21",
    },

    {
        id: 16,
        model: "Kia Ceed",
        year: 2019,
        mileage: 33770,
        status: "Свободен",
        driver: "Иванов С.",
        rating: 3.9,
        trips: 1529,
        fuel: "Petrol",
        class: "Standard",
        plate: "K172PE-77",
        service: "2023-10-13",
    },

    {
        id: 17,
        model: "Nissan Leaf",
        year: 2019,
        mileage: 312713,
        status: "Свободен",
        driver: "Новиков В.",
        rating: 4.3,
        trips: 15998,
        fuel: "Electric",
        class: "Economy",
        plate: "M294BB-77",
        service: "2024-11-05",
    },

    {
        id: 18,
        model: "Tesla Model 3",
        year: 2021,
        mileage: 252077,
        status: "Свободен",
        driver: "Иванов И.",
        rating: 3.9,
        trips: 11618,
        fuel: "Electric",
        class: "Business",
        plate: "B354EE-77",
        service: "2024-07-03",
    },

    {
        id: 19,
        model: "Nissan Leaf",
        year: 2018,
        mileage: 251187,
        status: "Свободен",
        driver: "Соколов С.",
        rating: 4.8,
        trips: 2970,
        fuel: "Electric",
        class: "Economy",
        plate: "O927PB-77",
        service: "2023-02-21",
    },

    {
        id: 20,
        model: "Renault Logan",
        year: 2016,
        mileage: 78896,
        status: "На обслуживании",
        driver: "Кузнецов Д.",
        rating: 4.2,
        trips: 16273,
        fuel: "Petrol",
        class: "Economy",
        plate: "E985MA-77",
        service: "2023-06-18",
    },

    {
        id: 21,
        model: "Tesla Model 3",
        year: 2016,
        mileage: 234693,
        status: "Свободен",
        driver: "Соколов П.",
        rating: 4.3,
        trips: 16447,
        fuel: "Electric",
        class: "Business",
        plate: "C294HE-77",
        service: "2025-09-18",
    },

    {
        id: 22,
        model: "Toyota Prius",
        year: 2024,
        mileage: 61959,
        status: "На заказе",
        driver: "Иванов А.",
        rating: 4.4,
        trips: 16977,
        fuel: "Hybrid",
        class: "Economy",
        plate: "P261AP-77",
        service: "2023-03-24",
    },

    {
        id: 23,
        model: "Skoda Octavia",
        year: 2017,
        mileage: 65631,
        status: "На заказе",
        driver: "Кузнецов Е.",
        rating: 3.9,
        trips: 8567,
        fuel: "Petrol",
        class: "Standard",
        plate: "T708AT-77",
        service: "2023-03-25",
    },

    {
        id: 24,
        model: "Tesla Model 3",
        year: 2024,
        mileage: 195868,
        status: "На обслуживании",
        driver: "Кузнецов О.",
        rating: 4.1,
        trips: 13469,
        fuel: "Electric",
        class: "Business",
        plate: "C787XH-77",
        service: "2024-04-13",
    },

    {
        id: 25,
        model: "Toyota Camry",
        year: 2017,
        mileage: 34883,
        status: "Свободен",
        driver: "Новиков И.",
        rating: 3.9,
        trips: 7484,
        fuel: "Petrol",
        class: "Comfort",
        plate: "P371CK-77",
        service: "2025-06-21",
    },

    {
        id: 26,
        model: "Hyundai Ioniq",
        year: 2019,
        mileage: 223738,
        status: "Свободен",
        driver: "Соколов А.",
        rating: 4.6,
        trips: 17832,
        fuel: "Hybrid",
        class: "Economy",
        plate: "A783PH-77",
        service: "2025-08-12",
    },

    {
        id: 27,
        model: "Hyundai Ioniq",
        year: 2018,
        mileage: 168656,
        status: "Свободен",
        driver: "Петров А.",
        rating: 4.0,
        trips: 9732,
        fuel: "Hybrid",
        class: "Economy",
        plate: "T315YK-77",
        service: "2023-07-28",
    },

    {
        id: 28,
        model: "VW Passat",
        year: 2024,
        mileage: 286131,
        status: "Свободен",
        driver: "Иванов И.",
        rating: 4.5,
        trips: 9566,
        fuel: "Diesel",
        class: "Comfort",
        plate: "A103KC-77",
        service: "2024-10-14",
    },

    {
        id: 29,
        model: "VW Passat",
        year: 2018,
        mileage: 261649,
        status: "На заказе",
        driver: "Попов А.",
        rating: 3.8,
        trips: 2965,
        fuel: "Diesel",
        class: "Comfort",
        plate: "Y252PA-77",
        service: "2025-05-04",
    },

    {
        id: 30,
        model: "Toyota Camry",
        year: 2024,
        mileage: 107643,
        status: "Свободен",
        driver: "Иванов П.",
        rating: 4.2,
        trips: 1807,
        fuel: "Petrol",
        class: "Comfort",
        plate: "K315XE-77",
        service: "2024-11-13",
    },

    {
        id: 31,
        model: "Hyundai Ioniq",
        year: 2021,
        mileage: 243058,
        status: "На обслуживании",
        driver: "Сидоров С.",
        rating: 4.8,
        trips: 6301,
        fuel: "Hybrid",
        class: "Economy",
        plate: "M125CY-77",
        service: "2025-08-04",
    },

    {
        id: 32,
        model: "Toyota Camry",
        year: 2022,
        mileage: 160111,
        status: "Свободен",
        driver: "Петров Е.",
        rating: 4.8,
        trips: 15923,
        fuel: "Petrol",
        class: "Comfort",
        plate: "E304OK-77",
        service: "2023-11-09",
    },

    {
        id: 33,
        model: "Kia Ceed",
        year: 2019,
        mileage: 42406,
        status: "На заказе",
        driver: "Попов О.",
        rating: 4.1,
        trips: 2774,
        fuel: "Petrol",
        class: "Standard",
        plate: "H459XP-77",
        service: "2024-02-14",
    },

    {
        id: 34,
        model: "Renault Logan",
        year: 2021,
        mileage: 44470,
        status: "Свободен",
        driver: "Смирнов Д.",
        rating: 4.4,
        trips: 9198,
        fuel: "Petrol",
        class: "Economy",
        plate: "A211TM-77",
        service: "2023-12-20",
    },

    {
        id: 35,
        model: "Toyota Camry",
        year: 2022,
        mileage: 298132,
        status: "Свободен",
        driver: "Новиков С.",
        rating: 4.1,
        trips: 14788,
        fuel: "Petrol",
        class: "Comfort",
        plate: "A632PX-77",
        service: "2025-01-06",
    },

    {
        id: 36,
        model: "Kia Ceed",
        year: 2021,
        mileage: 256124,
        status: "Свободен",
        driver: "Васильев В.",
        rating: 4.1,
        trips: 4583,
        fuel: "Petrol",
        class: "Standard",
        plate: "Y407PH-77",
        service: "2024-11-13",
    },

    {
        id: 37,
        model: "Tesla Model 3",
        year: 2021,
        mileage: 240973,
        status: "На заказе",
        driver: "Михайлов Д.",
        rating: 4.0,
        trips: 12923,
        fuel: "Electric",
        class: "Business",
        plate: "X866CT-77",
        service: "2024-08-05",
    },

    {
        id: 38,
        model: "VW Passat",
        year: 2022,
        mileage: 317276,
        status: "На заказе",
        driver: "Смирнов П.",
        rating: 4.0,
        trips: 11059,
        fuel: "Diesel",
        class: "Comfort",
        plate: "O552OX-77",
        service: "2023-08-07",
    },

    {
        id: 39,
        model: "Renault Logan",
        year: 2023,
        mileage: 118967,
        status: "На заказе",
        driver: "Смирнов А.",
        rating: 4.5,
        trips: 11483,
        fuel: "Petrol",
        class: "Economy",
        plate: "B938EX-77",
        service: "2023-11-14",
    },

    {
        id: 40,
        model: "Kia Ceed",
        year: 2019,
        mileage: 107255,
        status: "Свободен",
        driver: "Кузнецов М.",
        rating: 4.5,
        trips: 2886,
        fuel: "Petrol",
        class: "Standard",
        plate: "O524XT-77",
        service: "2023-07-19",
    },

    {
        id: 41,
        model: "Tesla Model 3",
        year: 2023,
        mileage: 239533,
        status: "Свободен",
        driver: "Иванов И.",
        rating: 4.7,
        trips: 7670,
        fuel: "Electric",
        class: "Business",
        plate: "C923YP-77",
        service: "2024-04-20",
    },

    {
        id: 42,
        model: "Toyota Prius",
        year: 2024,
        mileage: 160651,
        status: "На обслуживании",
        driver: "Петров М.",
        rating: 3.9,
        trips: 15725,
        fuel: "Hybrid",
        class: "Economy",
        plate: "X643PT-77",
        service: "2023-11-21",
    },

    {
        id: 43,
        model: "Nissan Leaf",
        year: 2024,
        mileage: 253735,
        status: "На заказе",
        driver: "Михайлов М.",
        rating: 4.8,
        trips: 16054,
        fuel: "Electric",
        class: "Economy",
        plate: "O365EX-77",
        service: "2023-10-11",
    },

    {
        id: 44,
        model: "Renault Logan",
        year: 2023,
        mileage: 155433,
        status: "Свободен",
        driver: "Петров П.",
        rating: 4.1,
        trips: 11505,
        fuel: "Petrol",
        class: "Economy",
        plate: "K653BC-77",
        service: "2023-06-04",
    },

    {
        id: 45,
        model: "Kia Ceed",
        year: 2022,
        mileage: 110113,
        status: "На заказе",
        driver: "Петров Е.",
        rating: 4.2,
        trips: 15767,
        fuel: "Petrol",
        class: "Standard",
        plate: "M163EM-77",
        service: "2024-02-03",
    },

    {
        id: 46,
        model: "Ford Focus",
        year: 2016,
        mileage: 229429,
        status: "Свободен",
        driver: "Васильев П.",
        rating: 4.6,
        trips: 14230,
        fuel: "Diesel",
        class: "Standard",
        plate: "P865YP-77",
        service: "2025-03-30",
    },

    {
        id: 47,
        model: "Ford Focus",
        year: 2019,
        mileage: 285972,
        status: "Свободен",
        driver: "Попов М.",
        rating: 3.8,
        trips: 11514,
        fuel: "Diesel",
        class: "Standard",
        plate: "X795MY-77",
        service: "2023-06-19",
    },

    {
        id: 48,
        model: "Nissan Leaf",
        year: 2018,
        mileage: 310034,
        status: "Свободен",
        driver: "Попов В.",
        rating: 4.4,
        trips: 1388,
        fuel: "Electric",
        class: "Economy",
        plate: "B758MC-77",
        service: "2025-06-06",
    },

    {
        id: 49,
        model: "Nissan Leaf",
        year: 2018,
        mileage: 56363,
        status: "Свободен",
        driver: "Васильев С.",
        rating: 4.3,
        trips: 11559,
        fuel: "Electric",
        class: "Economy",
        plate: "M384MH-77",
        service: "2025-05-04",
    },

    {
        id: 50,
        model: "Hyundai Ioniq",
        year: 2023,
        mileage: 40162,
        status: "На заказе",
        driver: "Иванов О.",
        rating: 4.0,
        trips: 2748,
        fuel: "Hybrid",
        class: "Economy",
        plate: "X141AE-77",
        service: "2023-07-24",
    },

    {
        id: 51,
        model: "Toyota Prius",
        year: 2018,
        mileage: 155066,
        status: "Свободен",
        driver: "Петров В.",
        rating: 4.8,
        trips: 15738,
        fuel: "Hybrid",
        class: "Economy",
        plate: "Y362KC-77",
        service: "2024-09-12",
    },

    {
        id: 52,
        model: "Ford Focus",
        year: 2017,
        mileage: 115860,
        status: "На обслуживании",
        driver: "Петров В.",
        rating: 3.8,
        trips: 10722,
        fuel: "Diesel",
        class: "Standard",
        plate: "T793MM-77",
        service: "2025-08-22",
    },

    {
        id: 53,
        model: "Kia Ceed",
        year: 2017,
        mileage: 157323,
        status: "Свободен",
        driver: "Смирнов В.",
        rating: 4.7,
        trips: 1845,
        fuel: "Petrol",
        class: "Standard",
        plate: "K645MX-77",
        service: "2024-01-15",
    },

    {
        id: 54,
        model: "Hyundai Ioniq",
        year: 2024,
        mileage: 208903,
        status: "Свободен",
        driver: "Попов М.",
        rating: 3.9,
        trips: 12368,
        fuel: "Hybrid",
        class: "Economy",
        plate: "X948OY-77",
        service: "2023-06-06",
    },

    {
        id: 55,
        model: "Tesla Model 3",
        year: 2018,
        mileage: 303545,
        status: "На обслуживании",
        driver: "Смирнов В.",
        rating: 4.7,
        trips: 16343,
        fuel: "Electric",
        class: "Business",
        plate: "O546YT-77",
        service: "2023-10-02",
    },

    {
        id: 56,
        model: "Toyota Camry",
        year: 2019,
        mileage: 75436,
        status: "Свободен",
        driver: "Соколов С.",
        rating: 4.6,
        trips: 12918,
        fuel: "Petrol",
        class: "Comfort",
        plate: "K129OK-77",
        service: "2023-07-06",
    },

    {
        id: 57,
        model: "Nissan Leaf",
        year: 2019,
        mileage: 216030,
        status: "На заказе",
        driver: "Васильев П.",
        rating: 4.8,
        trips: 9552,
        fuel: "Electric",
        class: "Economy",
        plate: "P110PE-77",
        service: "2023-03-29",
    },

    {
        id: 58,
        model: "Kia Ceed",
        year: 2022,
        mileage: 286155,
        status: "На заказе",
        driver: "Кузнецов М.",
        rating: 4.5,
        trips: 16583,
        fuel: "Petrol",
        class: "Standard",
        plate: "O911AB-77",
        service: "2023-10-29",
    },

    {
        id: 59,
        model: "Kia Ceed",
        year: 2022,
        mileage: 157561,
        status: "Свободен",
        driver: "Новиков О.",
        rating: 4.3,
        trips: 17897,
        fuel: "Petrol",
        class: "Standard",
        plate: "K535YP-77",
        service: "2023-12-05",
    },

    {
        id: 60,
        model: "Toyota Camry",
        year: 2023,
        mileage: 172038,
        status: "Свободен",
        driver: "Кузнецов И.",
        rating: 4.6,
        trips: 10839,
        fuel: "Petrol",
        class: "Comfort",
        plate: "B860PY-77",
        service: "2023-07-09",
    },

];
